apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-k8s-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-k8s-server
  template:
    metadata:
      labels:
        app: go-k8s-server
    spec:
      containers:
        - name: go-k8s-container
          image: nsahil992/go-k8s-server
          ports:
            - containerPort: 8080